version: 2
jobs:
  build:

    branches:
      only:
        - master

    docker:
      - image: circleci/node:8.7

    working_directory: ~/repo

    steps:
      # AWS Installation and Config
      - run: sudo apt-get -y -qq install awscli
      - run: mkdir /home/circleci/.aws
      - run: touch /home/circleci/.aws/config
      - run: chmod 600 ~/.aws/config
      - run: echo "[preview]" > /home/circleci/.aws/config
      - run: echo "cloudfront=true" >> /home/circleci/.aws/config

      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn build
      - run: aws s3 sync ./build/ s3://$S3_BUCKET_NAME --delete
      - run: echo '{"Paths": {"Quantity": 1, "Items": ["/index.html"]}, "CallerReference": "iridium-dog-$CIRCLE_BUILD_NUM"}' > ib.json
      - run: cat ib.json
      - run: aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION --invalidation-batch file://ib.json
